### ISSUE TITLE
Migrate to Next

### ISSUE THREAD

**Issue by fredrir** [appKom/onlinefondet#54]
Ugrade to latest next version. In order to set up some API routes and backend for admin page

**Comment by julian-ao** [comment]
rett etter at jeg refaktorerte til vite 😢

**Comment by fredrir** [comment]
> rett etter at jeg refaktorerte til vite 😢

Er det mulig å sette opp API routes med vite? Er ikke så kjent med det

**Comment by fredrir** [comment]
> rett etter at jeg refaktorerte til vite 😢

Kan evnt sette opp en egen backend, så det var grusomt mye migrering som måtte til for å migrere

**Comment by julian-ao** [comment]
tror ikke det er innebygd i vite nei. skal vel være ganske straight forward å flytte over til next.js. er nok lettest det kanskje?

**Comment by fredrir** [comment]
> tror ikke det er innebygd i vite nei. skal vel være ganske straight forward å flytte over til next.js. er nok lettest det kanskje?

Tror nok kanskje det er det enkleste, og da kan vi lett skalere med tanke på et admin dashbord.
